"""agregar FK real de servicio.id en Cita y Venta

Revision ID: 04e66a2dc56f
Revises: cc43e88f6c21
Create Date: 2026-08-11 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e66a2dc56f'
down_revision = 'cc43e88f6c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, 'servicio', ['servicio_id'], ['id'])

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, 'servicio', ['servicio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
    # ### end Alembic commands ###
