"""campos de password temporal y reset en Usuario

Revision ID: 0723ba5c624b
Revises: 832069ccea68
Create Date: 2026-08-08 16:50:47.281605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0723ba5c624b'
down_revision = '832069ccea68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expira', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expira')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('debe_cambiar_password')

    # ### end Alembic commands ###
