"""empty message

Revision ID: 13442a49ca7e
Revises: 4d06bb5e65d3
Create Date: 2026-08-09 01:10:57.000736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13442a49ca7e'
down_revision = '4d06bb5e65d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('firma', sa.String(length=300), nullable=True),
    sa.Column('fecha_firma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expediente_clinico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('alergias', sa.String(length=250), nullable=True),
    sa.Column('cirugias', sa.String(length=250), nullable=True),
    sa.Column('enfermedades_cronicas', sa.String(length=250), nullable=True),
    sa.Column('medicamentos', sa.String(length=250), nullable=True),
    sa.Column('embarazo_lactancia', sa.String(length=250), nullable=True),
    sa.Column('fototipo', sa.String(length=50), nullable=True),
    sa.Column('sensibilidad', sa.String(length=250), nullable=True),
    sa.Column('tratamientos_previos', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_evolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('parametros_usados', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto_evolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historial_clinico')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('ocupacion', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['telefono'])
        batch_op.drop_column('alergias')
        batch_op.drop_column('nombre_completo')
        batch_op.drop_column('tipo_piel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_piel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_completo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('alergias', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ocupacion')
        batch_op.drop_column('nombre')

    op.create_table('historial_clinico',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cita_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('foto_antes_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('foto_despues_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], name=op.f('historial_clinico_cita_id_fkey')),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('historial_clinico_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historial_clinico_pkey'))
    )
    op.drop_table('foto_evolucion')
    op.drop_table('bitacora_evolucion')
    op.drop_table('expediente_clinico')
    op.drop_table('consentimiento')
    # ### end Alembic commands ###
