"""fix: conectar FormaPagoPaquete y EstadoPaquete como Enum

Revision ID: 1881c7e0768f
Revises: 86bbb97a6588
Create Date: 2026-08-09 02:36:15.182823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1881c7e0768f'
down_revision = '86bbb97a6588'
branch_labels = None
depends_on = None


def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        formapagopaquete_enum = sa.Enum('CONTADO', 'PLAZOS', name='formapagopaquete')
        formapagopaquete_enum.create(op.get_bind(), checkfirst=True)

        estadopaquete_enum = sa.Enum('ACTIVO', 'AGOTADO', name='estadopaquete')
        estadopaquete_enum.create(op.get_bind(), checkfirst=True)

        with op.batch_alter_table('paquete_paciente', schema=None) as batch_op:
            batch_op.alter_column('forma_pago',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('CONTADO', 'PLAZOS', name='formapagopaquete'),
                   existing_nullable=False,
                   postgresql_using='forma_pago::formapagopaquete') # ⬅️ AGREGAR ESTA LÍNEA
            batch_op.alter_column('estado',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('ACTIVO', 'AGOTADO', name='estadopaquete'),
                   existing_nullable=False,
                   postgresql_using='estado::estadopaquete') # ⬅️ AGREGAR ESTA LÍNEA

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquete_paciente', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ACTIVO', 'AGOTADO', name='estadopaquete'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('forma_pago',
               existing_type=sa.Enum('CONTADO', 'PLAZOS', name='formapagopaquete'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
