"""empty message

Revision ID: 412bb25ac91b
Revises: ef4e77564c6c
Create Date: 2026-08-09 01:38:18.675292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412bb25ac91b'
down_revision = 'ef4e77564c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=120), nullable=False))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre_completo')

    # ### end Alembic commands ###
