"""fix: agregar cita_id y actualizar modelo

Revision ID: 51f9e127713c
Revises: b7ec2f6c3e1e
Create Date: 2026-08-09 03:22:45.842779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51f9e127713c'
down_revision = 'b7ec2f6c3e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto_fijo')
    op.drop_table('paquete_paciente')
    op.drop_table('venta')
    op.drop_table('comision')
    op.drop_table('pago')
    with op.batch_alter_table('historial_clinico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cita_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cita', ['cita_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_clinico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cita_id')

    op.create_table('pago',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('pago_venta_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pago_pkey'))
    )
    op.create_table('comision',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('especialista_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mes', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pagada', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['especialista_id'], ['usuario.id'], name=op.f('comision_especialista_id_fkey')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('comision_venta_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comision_pkey'))
    )
    op.create_table('venta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cita_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paquete_paciente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monto_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], name=op.f('venta_cita_id_fkey')),
    sa.ForeignKeyConstraint(['paquete_paciente_id'], ['paquete_paciente.id'], name=op.f('venta_paquete_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('venta_pkey'))
    )
    op.create_table('paquete_paciente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paquete_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_compra', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('forma_pago', postgresql.ENUM('CONTADO', 'PLAZOS', name='formapagopaquete'), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('ACTIVO', 'AGOTADO', name='estadopaquete'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('paquete_paciente_pkey'))
    )
    op.create_table('gasto_fijo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('concepto', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gasto_fijo_pkey'))
    )
    # ### end Alembic commands ###
