"""modelo Cita

Revision ID: 832069ccea68
Revises: fcb09fb059fe
Create Date: 2026-08-08 15:52:05.404895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832069ccea68'
down_revision = 'fcb09fb059fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('paquete_paciente_sesion_id', sa.Integer(), nullable=True),
    sa.Column('especialista_id', sa.Integer(), nullable=False),
    sa.Column('espacio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('AGENDADA', 'REPROGRAMADA', 'COMPLETADA', 'CANCELADA', name='estadocita'), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacio_trabajo.id'], ),
    sa.ForeignKeyConstraint(['especialista_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita')
    # ### end Alembic commands ###
