"""add google_calendar_id a clinica

Revision ID: 8c7ff9173b3e
Revises: 3558364fa2eb
Create Date: 2026-09-06 17:00:51.022143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7ff9173b3e'
down_revision = '3558364fa2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_id')

    # ### end Alembic commands ###
