"""empty message

Revision ID: 9023b4e90c6f
Revises: 31ba0cc519d1
Create Date: 2026-09-02 01:34:09.587751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9023b4e90c6f'
down_revision = '31ba0cc519d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=255), nullable=False),
                    sa.Column('tipo', sa.Enum('CLIENTE', 'ASISTENTE', 'ESPECIALISTA', name='tipoinvite'), nullable=False),
                    sa.Column('paciente_id', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('usado', sa.Boolean(), nullable=False),
                    sa.Column('expira', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('paciente_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('paciente_telefono_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('paciente_telefono_key'), ['telefono'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('paciente_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('activo')
        batch_op.drop_column('google_id')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    op.drop_table('invite')
    # ### end Alembic commands ###
