"""add servicio model

Revision ID: cc43e88f6c21
Revises: fd29602c5a1b
Create Date: 2026-08-11 02:09:00.713824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc43e88f6c21'
down_revision = 'fd29602c5a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('porcentaje_comision', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio')
    # ### end Alembic commands ###
