"""Agregar tablas de ventas, pagos, comisiones y gastos fijos

Revision ID: d94513d1ee72
Revises: 832069ccea68
Create Date: 2026-08-09 00:23:59.845282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94513d1ee72'
down_revision = '832069ccea68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto_fijo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquete_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('paquete_id', sa.Integer(), nullable=True),
    sa.Column('fecha_compra', sa.DateTime(), nullable=False),
    sa.Column('forma_pago', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('paquete_paciente_id', sa.Integer(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
    sa.ForeignKeyConstraint(['paquete_paciente_id'], ['paquete_paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialista_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('mes', sa.DateTime(), nullable=False),
    sa.Column('pagada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['especialista_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('comision')
    op.drop_table('venta')
    op.drop_table('paquete_paciente')
    op.drop_table('gasto_fijo')
    # ### end Alembic commands ###
