"""empty message

Revision ID: ef4e77564c6c
Revises: 13442a49ca7e
Create Date: 2026-08-09 01:26:50.838752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef4e77564c6c'
down_revision = '13442a49ca7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_clinico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('alergias', sa.String(length=250), nullable=True),
    sa.Column('tipo_piel', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('foto_antes_url', sa.String(length=300), nullable=True),
    sa.Column('foto_despues_url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bitacora_evolucion')
    op.drop_table('consentimiento')
    op.drop_table('foto_evolucion')
    op.drop_table('expediente_clinico')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_consentimiento', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('fecha_firma_consentimiento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('fecha_firma_consentimiento')
        batch_op.drop_column('firma_consentimiento')

    op.create_table('expediente_clinico',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alergias', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cirugias', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enfermedades_cronicas', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('medicamentos', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('embarazo_lactancia', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('fototipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sensibilidad', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tratamientos_previos', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('expediente_clinico_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('expediente_clinico_pkey'))
    )
    op.create_table('foto_evolucion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cita_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], name=op.f('foto_evolucion_cita_id_fkey')),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('foto_evolucion_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('foto_evolucion_pkey'))
    )
    op.create_table('consentimiento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firma', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('fecha_firma', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('consentimiento_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consentimiento_pkey'))
    )
    op.create_table('bitacora_evolucion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cita_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observaciones', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('parametros_usados', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], name=op.f('bitacora_evolucion_cita_id_fkey')),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('bitacora_evolucion_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bitacora_evolucion_pkey'))
    )
    op.drop_table('historial_clinico')
    # ### end Alembic commands ###
