"""add google_id and email

Revision ID: f7417f1596a8
Revises: a9319846ad7c
Create Date: 2026-09-04 03:36:33.620404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7417f1596a8'
down_revision = 'a9319846ad7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        # En SQLite (dev local) estos dos uniques globales quedan como indices
        # anonimos al recrear la tabla en migraciones anteriores -- no
        # conservan el nombre 'paciente_cedula_key'/'paciente_telefono_key'
        # que si tiene Postgres (donde la columna se declaro unique desde el
        # diseño mono-clinica original). Dropearlos por nombre en SQLite
        # truena con "No such constraint", asi que se omite ahi: el indice
        # anonimo se queda (redundante con el UniqueConstraint compuesto de
        # clinica_id+cedula/telefono de a9319846ad7c, sin efecto practico mas
        # alla de que en dev local con SQLite un telefono/cedula no se puede
        # repetir entre clinicas distintas -- si eso llega a bloquear una
        # prueba local, es un artefacto de SQLite, no de Postgres/produccion).
        if bind.dialect.name != 'sqlite':
            batch_op.drop_constraint(batch_op.f('paciente_cedula_key'), type_='unique')
            batch_op.drop_constraint(batch_op.f('paciente_telefono_key'), type_='unique')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        # Nombre explicito (no None) -- el batch mode de SQLite exige nombre
        # en el momento de la llamada, a diferencia de Postgres que puede
        # resolverlo solo via naming convention. Mismo nombre que ya
        # esperaba downgrade() de este archivo.
        batch_op.create_unique_constraint('usuario_google_id_key', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('usuario_google_id_key'), type_='unique')
        batch_op.drop_column('google_id')

    if bind.dialect.name != 'sqlite':
        # Ver nota en upgrade(): en SQLite estos nunca se dropearon (siguen
        # como indice anonimo), asi que no hay nada que recrear ahi.
        with op.batch_alter_table('paciente', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('paciente_telefono_key'), ['telefono'], postgresql_nulls_not_distinct=False)
            batch_op.create_unique_constraint(batch_op.f('paciente_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
