"""paciente e historial clinico

Revision ID: fd29602c5a1b
Revises: 1881c7e0768f
Create Date: 2026-08-09 04:48:42.714945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd29602c5a1b'
down_revision = '1881c7e0768f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nombre_completo', sa.String(
                        length=120), nullable=False),
                    sa.Column('cedula', sa.String(length=50), nullable=False),
                    sa.Column('telefono', sa.String(
                        length=20), nullable=False),
                    sa.Column('ocupacion', sa.String(
                        length=120), nullable=True),
                    sa.Column('edad', sa.Integer(), nullable=True),
                    sa.Column('firma_consentimiento', sa.String(
                        length=300), nullable=True),
                    sa.Column('fecha_firma_consentimiento',
                              sa.DateTime(), nullable=True),
                    sa.Column('alergias', sa.String(
                        length=250), nullable=True),
                    sa.Column('tipo_piel', sa.String(
                        length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('cedula'),
                    sa.UniqueConstraint('telefono')
                    )
    op.create_table('historial_clinico',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('paciente_id', sa.Integer(), nullable=False),
                    sa.Column('cita_id', sa.Integer(), nullable=False),
                    sa.Column('observaciones', sa.String(
                        length=500), nullable=True),
                    sa.Column('foto_antes_url', sa.String(
                        length=300), nullable=True),
                    sa.Column('foto_despues_url', sa.String(
                        length=300), nullable=True),
                    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
                    sa.ForeignKeyConstraint(
                        ['paciente_id'], ['paciente.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'paciente', ['paciente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')


