"""Modulo der control de acceso basado en roles y matriz de permisos de SOMA"""


PERMISOS_POR_ROL = {
        "admin": {
            "dashboard:global",
            "dashboard:matriz_permisos",
            "agenda:crear",
            "agenda:editar",
            "agenda:ver_global",
            "pacientes:alta",
            "pacientes:ver",
            "expediente:ver",
            "consentimientos:generar",
            "consentimientos:verificar",
            "ventas:registrar",
            "ventas:ver",
            "inventario:editar",
            "servicios:crear",
            "servicios:editar_eliminar",
            "paquetes:crud",
            "espacios:crud",
            "usuarios:crear",
            "comisiones:reporte_global",
            "caja:cerrar",
        },
        "asistente": {
            "agenda:crear",
            "agenda:editar",
            "agenda:ver_global",
            "pacientes:alta",
            "pacientes:ver",
            "expediente:captura_inicial",
            "consentimientos:generar",
            "ventas:registrar",
            "ventas:ver",
            "inventario:editar",
            "servicios:crear",
            "paquetes:crud",
            "caja:conteo",
        },
        "especialista": {
            "dashboard:propio",
            "agenda:ver_global",
            "agenda:reagendar_propia",
            "pacientes:ver",
            "expediente:crear_editar",
            "consentimientos:verificar",
            "inventario:descuento_auto",
            "comisiones:reporte_propio",
        },
    }
MATRIZ_PERMISOS = [
        {
            "id": 1,
            "modulo": "Dashboard completo",
            "accion": "dashboard:global",
            "descripcion": "Ingresos globales, balance y todas las comisiones",
            "admin": "✅ Permitido",
            "asistente": "❌ Sin acceso",
            "especialista": "❌ Sin acceso",
        },
        {
            "id": 2,
            "modulo": "Dashboard propio",
            "accion": "dashboard:propio",
            "descripcion": "Sesiones y comisiones individuales del día",
            "admin": "—",
            "asistente": "—",
            "especialista": "✅ Solo lo suyo",
        },
        {
            "id": 3,
            "modulo": "Agenda (Citas)",
            "accion": "agenda:ver_global",
            "descripcion": "Crear, consultar y editar citas",
            "admin": "✅ Crear / Editar / Ver todo",
            "asistente": "✅ Crear / Editar / Ver todo",
            "especialista": "👁️ Ver Agenda Global / Reagendar la suya",
        },
        {
            "id": 4,
            "modulo": "Pacientes",
            "accion": "pacientes:ver",
            "descripcion": "Alta y consulta de datos básicos de pacientes",
            "admin": "✅ Permitido",
            "asistente": "✅ Permitido",
            "especialista": "👁️ Solo consulta",
        },
        {
            "id": 5,
            "modulo": "Expediente clínico",
            "accion": "expediente:ver",
            "descripcion": "Anamnesis, bitácora y fotos antes/después",
            "admin": "👁️ Ver",
            "asistente": "📝 Ver / Captura inicial",
            "especialista": "✏️ Crear / Editar",
        },
        {
            "id": 6,
            "modulo": "Consentimientos informados",
            "accion": "consentimientos:generar",
            "descripcion": "Firma digital y validación",
            "admin": "📜 Generar / Verificar",
            "asistente": "📜 Generar",
            "especialista": "✍️ Verificar firma",
        },
        {
            "id": 7,
            "modulo": "Ventas y cobros",
            "accion": "ventas:registrar",
            "descripcion": "Registro de ventas, abonos y transacciones",
            "admin": "✅ Permitido",
            "asistente": "✅ Permitido",
            "especialista": "❌ Sin acceso",
        },
        {
            "id": 8,
            "modulo": "Inventario",
            "accion": "inventario:editar",
            "descripcion": "Gestión de stock e insumos",
            "admin": "✏️ Editar",
            "asistente": "✏️ Editar",
            "especialista": "⚡ Descuento automático",
        },
        {
            "id": 9,
            "modulo": "Catálogo → Servicios (Crear)",
            "accion": "servicios:crear",
            "descripcion": "Crear nuevos servicios en el catálogo",
            "admin": "✅ Permitido",
            "asistente": "✅ Permitido",
            "especialista": "❌ Sin acceso",
        },
        {
            "id": 10,
            "modulo": "Catálogo → Servicios (Editar/Eliminar)",
            "accion": "servicios:editar_eliminar",
            "descripcion": "Modificar o eliminar servicios existentes",
            "admin": "✅ Permitido",
            "asistente": "❌ Sin acceso",
            "especialista": "❌ Sin acceso",
        },
        {
            "id": 11,
            "modulo": "Catálogo → Paquetes",
            "accion": "paquetes:crud",
            "descripcion": "CRUD completo de paquetes de tratamiento",
            "admin": "✅ Permitido",
            "asistente": "✅ Permitido",
            "especialista": "❌ Sin acceso",
        },
        {
            "id": 12,
            "modulo": "Espacios de trabajo",
            "accion": "espacios:crud",
            "descripcion": "Gestión de salas, camas y estaciones",
            "admin": "✅ Permitido",
            "asistente": "❌ Sin acceso",
            "especialista": "❌ Sin acceso",
        },
        {
            "id": 13,
            "modulo": "Crear usuarios",
            "accion": "usuarios:crear",
            "descripcion": "Alta de Asistentes y Especialistas",
            "admin": "✅ Permitido",
            "asistente": "❌ Sin acceso",
            "especialista": "❌ Sin acceso",
        },
        {
            "id": 14,
            "modulo": "Reporte de comisiones",
            "accion": "comisiones:reporte_global",
            "descripcion": "Visualización global de comisiones",
            "admin": "✅ Completo",
            "asistente": "❌ Sin acceso",
            "especialista": "👁️ Solo las propias",
        },
        {
            "id": 15,
            "modulo": "Cierre de caja",
            "accion": "caja:cerrar",
            "descripcion": "Validación y cierre de caja diario",
            "admin": "🔒 Cierra",
            "asistente": "📋 Registra conteo",
            "especialista": "❌ Sin acceso",
        },
    ]

def tiene_permiso(rol: str, accion: str) -> bool:
        """Verifica si un rol posee el permiso para ejecutar una acción específica."""
        permisos_rol = PERMISOS_POR_ROL.get(rol, set())
        return accion in permisos_rol

def obtener_matriz_permisos() -> list:
        """Retorna la matriz de permisos estructurada para la API."""
        return MATRIZ_PERMISOS